### ISSUE TITLE
Requirements Document

### ISSUE THREAD

**Issue by lflanagan7** [Hire-Wire/hire-wire#4]
Functional and non-functional requirements
User stories

**Comment by stevenhcau** [comment]
Finalized requirements and user stories. Document is on drive. Document is called "User Stories and Requirements - October 16.xlsx"

Also located at: https://docs.google.com/spreadsheets/d/17JNXcFd8K3cM00N7UuhOUgITym0IFzab/edit?usp=drive_link&ouid=106927972886553008322&rtpof=true&sd=true

[User Stories and Requirements - October 16.xlsx](https://github.com/user-attachments/files/17405863/User.Stories.and.Requirements.-.October.16.xlsx)

**Comment by stevenhcau** [comment]
Closing issue to ensure we achieve alignment on requirements. Any issues or additions can be raised in this chain to make changes to the Requirements document.

**Comment by stevenhcau** [comment]
Edit: reopened, maybe it is better to keep as an open issue until project is done?
