### ISSUE TITLE
ER Diagram

### ISSUE THREAD

**Issue by lflanagan7** [Hire-Wire/hire-wire#6]
ER diagram with key entities, attributes, relationships, cardinalities, any specializations or weak entities in system
Submit as image or pdf file

**Comment by roxmai** [comment]
![608 Project ER Diagram Rev0](https://github.com/user-attachments/assets/d806cdaf-3911-49e0-b89f-c1c921e2f5d0)

Ready to review on Oct 14, 2024

Questions from creating ER Diagram
1. (Generalization) Add Document Entities to share common attributes for Resume and CoverLetter?
2. generalization) Add Experience Entities for Education, Employment, Volunteer? (avoid too many tables and be flexible)
"
ExperienceId (Primary Key)
UserId (Foreign Key to User.user_id)
ExperienceType (Enum: 'Education', 'Employment', 'Volunteer')
Organization
RoleName (for Employment and Volunteer)
Degree (for Education)
StartDate
EndDate"

3. (specialization) Add specialized entities (certification, license) inheriting from Credential

Edition Log
Rev 0 - (Oct 14, 2024) - Roxanne
Based on Class Diagram Rev A & Rev B has been told Rev A is outdated but Rev B is not completed.

**Comment by roxmai** [comment]
![608 Project ER Diagram Rev1](https://github.com/user-attachments/assets/8dad7916-4aa9-4397-880f-cbe7345ace4d)

ER Diagram updated on creating generalization entities "Document" & "Experience" and put placeholder entity for FormatSetting. Rev1 uploaded in project drive.
