### ISSUE TITLE
Logical Schema

### ISSUE THREAD

**Issue by lflanagan7** [Hire-Wire/hire-wire#7]
Based on ER diagram develop schema with tables, primary keys, foreign keys and normalization
Submit as image

**Comment by roxmai** [comment]
[608 Logical Schema Rev1.docx](https://github.com/user-attachments/files/17403224/608.Logical.Schema.Rev1.docx)

Logical Schema is updated based on meeting on Oct 16. Primary key, foreign key, and attributes are confirmed. Entities will expand or shrink based along with the project develop. Please note FormatSetting is not in logical schema but should add once known more about how this FormatSetting works.
